name: Install Yarn Dependencies
description: Installs Yarn Dependencies
runs:
  using: 'composite'
  steps:
    # Install Yarn v2 dependencies
    - uses: actions/setup-node@v4.2.0
      with:
        node-version-file: '.nvmrc'

    - run: npm install -g "yarn@1.22.19"
      shell: bash

    - uses: actions/cache@v4.2.0
      id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
      with:
        path: |
          .yarn/cache
          .yarn/unplugged
          .yarn/install-state.gz
          .pnp.cjs
        key: ${{ runner.os }}-${{ runner.arch }}-yarn-v10-${{ hashFiles('**/yarn.lock', '**/package.json') }}
        restore-keys: |
          ${{ runner.os }}-${{ runner.arch }}-yarn-v10-
    - uses: nick-fields/retry@v3
      if: steps.yarn-cache.outputs.cache-hit != 'true' || inputs.force-yarn-install == 'true'
      with:
        timeout_minutes: 10
        max_attempts: 3
        retry_on: error
        command: yarn install --immutable
